name: build_compatible

on: 
  push:
    paths: 
      - build/**
      - .github/workflows/build_compatible.yml

jobs:    
  windows:
    runs-on: windows-2016
    steps:
      - uses: actions/checkout@v2
      
      - name: Insatll MSVC
        uses: microsoft/setup-msbuild@v1.0.2
      
      - name: Build
        run: |
          cd build
          .\make_win64_lua53_compatible.bat
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Upload53
        uses: actions/upload-artifact@v2
        with:
          path: ./build/plugin_lua53/**/*
          name: plugin_lua53   
    

   
